---
- name: Delete Infrastructure
  hosts: local
  gather_facts: false
  tasks:
    - name: Delete Infrastructure
      tags: [infra]
      block:
        - name: Calculate config vars
          ansible.builtin.include_role:
            name: config
            public: true
        - name: Force Error # noqa command-instead-of-shell no-changed-when
          ansible.builtin.shell: exit 1
          vars:
            error: false
          when: error
        - name: Delete Infrastructure
          ansible.builtin.include_role:
            name: down_infra
- name: Delete Base Resources
  hosts: local
  gather_facts: false
  tasks:
    - name: Delete Base Resources
      block:
        - name: Calculate config vars
          ansible.builtin.include_role:
            name: config
            public: true
        - name: Initialize
          ansible.builtin.include_role:
            name: down_init
- name: Cleanup
  hosts: local
  gather_facts: false
  tasks:
    - name: Cleanup
      tags: [cleanup]
      block:
        - name: Calculate config vars
          ansible.builtin.include_role:
            name: config
            public: true
        - name: Delete secrets
          ansible.builtin.include_role:
            name: delete_secrets
