---
- name: Set config project
  ansible.builtin.set_fact:
    config_project: "{{ config_project_base }}-{{ config_project_instance }}"
- name: Set config key_name
  ansible.builtin.set_fact:
    config_key_name: "{{ config_project }}"
- name: Set config EC2 key pair private key Secrets Manager Secret
  ansible.builtin.set_fact:
    config_ec2_key_pair_secret_name: "/{{ config_project_base }}/{{ config_project_instance }}/ec2-keypair-secret"
- name: Set config SSH private file path
  ansible.builtin.set_fact:
    config_ssh_file: "{{ config_local_secrets_folder }}/{{ config_key_name }}"
