---
- name: Set config project
  ansible.builtin.set_fact:
    config_project: "{{ config_project_base }}-{{ config_project_instance }}"
- name: Set config key_name
  ansible.builtin.set_fact:
    config_key_name: "{{ config_project }}"
- name: Set config EC2 key pair private key Secrets Manager Secret
  ansible.builtin.set_fact:
    config_ec2_key_pair_secret_name: "/{{ config_project_base }}/{{ config_project_instance }}/ec2-keypair-secret"
- name: Set config SSH private file path
  ansible.builtin.set_fact:
    config_ssh_file: "{{ config_local_secrets_folder }}/{{ config_key_name }}"
- name: Get AWS Account ID
  amazon.aws.aws_caller_info:
  register: config_caller_info
- name: Set config AWS Account ID
  ansible.builtin.set_fact:
    config_aws_account_id: "{{ config_caller_info.account }}"
- name: Set config S3 bucket and key
  ansible.builtin.set_fact:
    config_terraform_s3_bucket: "k8s-aws-{{ config_aws_account_id }}"
    config_terraform_s3_key: "{{ config_project }}/terraform/state"
- name: Get AWS AZ info
  amazon.aws.aws_az_info:
  register: config_aws_az_info
- name: Get AWS Region
  ansible.builtin.set_fact:
    config_region: "{{ config_aws_az_info.availability_zones[0]['region_name'] }}"
