---
- name: Create new EC2 keypair
  amazon.aws.ec2_key:
    name: "{{ config_key_name }}"
    region: "{{ config_region }}"
  register: init_ec2_key
- name: Save Private Key to AWS Secrets Manager
  community.aws.secretsmanager_secret:
    description: Private key for EC2 keypair for {{ config_project }}
    name: "{{ config_ec2_key_pair_secret_name }}"
    region: "{{ config_region }}"
    secret: "{{ init_ec2_key.key.private_key }}"
    tags:
      Project: "{{ config_project }}"
  when: init_ec2_key.changed # noqa no-handler
