name: Check after commit

on:
  push:
    paths-ignore:
      - ".github/**"
jobs:

  lint:
    name: Lint all the things
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ansible/ansible-lint-action@main
  