name: Deploy

on:
  workflow_dispatch: {}

jobs:

  deploy:
  
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      
    steps:
    
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          role-session-name: GitHub-Action-Deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Test
        run: aws ec2 describe-vpcs
