name: Deploy

on:
  workflow_dispatch: {}

jobs:

  deploy:
  
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      
    steps:
    
      - uses: hashicorp/setup-terraform@v2
      - run: pip install ansible-lint botocore boto3  
      - run: ansible-galaxy collection install amazon.aws community.general community.aws 
      - run: ansible --version
      - run: terraform --version
      - run: python --version
      - run: pip --version
      - run: ansible-galaxy collection list
      
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          role-session-name: GitHub-Action-Deploy
          aws-region: ${{ vars.AWS_REGION }}

      - run: mkdir -p secrets # TODO: put this in playbook
      - run: ./up -e config_project_instance=github -vvvv
